### ISSUE TITLE
Strange moment tensor to fault plane behaviour

### ISSUE THREAD

**Issue by shicks-seismo** [djpugh/MTfit#42]
Hi David,
The following moment tensor configuration plots incorrectly and produces the incorrect fault planes
```
mt = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, -1.0, 0.0]])
a = mtfit.convert.MT33_SDR(np.array(mt))
print("a", np.degrees(a))
```
Seems like there is some numerical issue for this particular case. Most other MT configurations seem to work ok.

**Comment by djpugh** [comment]
@shicks-seismo - sorry, context switching back to this from a day doing something completely different, can you let me know what output you are getting, what you expect and what version you are running?

**Comment by djpugh** [comment]
I think I found this issue - I will update the code on here (on the develop branch and prepare a new release)

**Comment by shicks-seismo** [comment]
Great! Thanks, David! (p.s. I share an office with Tim Greenfield at Southampton - he is the one that introduced me to MTfit!
