### ISSUE TITLE
inconsistent station propagation coefficients with Pugh et al. 2016 Appendix A

### ISSUE THREAD

**Issue by hvasbath** [djpugh/MTfit#66]
*Please fill in the following details as much as possible when submitting your issue as this will help with testing and reproducing the issue*

## Environment Information
 *use `(print(MTfit.get_details_json()))` in a python terminal (or `MTfit --details` from the command line)*

## What error you are getting
I studied your paper Pugh et al. 2016 A Bayesian method for microseismic source inversion
where you list in appendix A the station propagation coefficients. Thanks a lot for this! Nevertheless, I was comparing your notation from the paper with the station_angles function implementation in inversion.py l. https://github.com/djpugh/MTfit/blob/develop/src/MTfit/inversion.py#L3217

Some of these lines are vastly inconsistent with the equations from the paper. Do you use a different coordinate system here or other transformations, that I did not find? Thanks a lot for your response!

## What behaviour you would expect
Consistent implementation to paper.

## Reproduction steps
What do we need to do to reproduce the issue?

**Comment by djpugh** [comment]
Thanks @hvasbath  - I'll need to refamiliarise myself with the formulation as I haven't actually been working in this space for a while to double check - but I believe the difference is because in MTfit the 6 vector is ordered as:
        Mxx
        Myy
        Mzz
        sqrt(2)*Mxy
        sqrt(2)*Mxz
        sqrt(2)*Myz

While in the paper it is ordered as (for consistency with Chapman (?) IIRC)
        Mxx
        Myy
        Mzz
        sqrt(2)*Myz
        sqrt(2)*Mxz
        sqrt(2)*Mxy

Plus there is some expansion of double angles as well
I've added some comments to the code in the PR #67 - please could you check that it makes sense to you - i will try and double check later after work as well

**Comment by hvasbath** [comment]
Hi @djpugh ,

thanks a lot for the clarification! The double-angles hint resolves everyhing, but I wonder why you do that, because numerically its two times faster to calculate sin(2x) instead of 2sin(x)cos(x).

**Comment by djpugh** [comment]
TBH, I can't remember why, it's a good point (in fact should probably cache the cos and sin values - I think because it is a one off calculation per run, I probably didn't focus on it

**Comment by hvasbath** [comment]
FYI, was testing eq A7-A9 against A15-A17.
Found the error. Its in equation A2 Appendix A.
Must be in third component -sin(take-off angles) instead of sin(take-off angles). Its just a typo comparing to Aki and RIchards.
Again thanks a lot!
