### ISSUE TITLE
Run Automatic Bayesian Polarity

### ISSUE THREAD

**Issue by rcabdia** [djpugh/MTfit#69]
Dear djpugh

Me and my team would like to include the algorithm to automatic determination of Polarity in "Integrated Seismic Program":
**Pugh, D J, White, R S and Christie, P A F, 2016b, Automatic Bayesian polarity determination, GJI, 206(1), 275-291.**

However, I cannot find it anywhere. Please do you mind let a link to download it or send it this via,
Thank you very much in advance!

Best Regards,

Roberto Cabieces

**Comment by djpugh** [comment]
Hi @rcabdia, apologies - I never got notifications for this, unfortunately the ownership and permissions to publish that specific code were not granted to me (due to IP ownership), however the algorithm is very simple, and can be implemented pretty easily from the paper mentioned.
